import type { Ui } from '../../types';

export const uiEn: Ui = {
  videoMirror: 'Mirror on RuTube',
  videoMirrorYoutube: 'Mirror on YouTube',
  videoPlay: 'Play video',
  videoLoading: 'Loading',
  backToHome: 'Back to home',
  navBack: 'Home',
  navCases: 'Case',
  sectionAbout: 'About',
  sectionCases: 'Demo cases',
  sectionTimeline: 'Timeline',
  sectionStack: 'Stack',
  caseSectionContext: 'Context',
  caseHeroFacts: 'Facts',
  caseSectionArchitecture: 'Architecture',
  caseSectionDecisions: 'Key engineering decisions',
  caseSectionStack: 'Stack',
  caseSectionLessons: 'Lessons & status',
  caseLessonsKeep: 'Carry forward',
  caseLessonsChange: 'Would change',
  caseDecision: 'Decision',
  caseWhy: 'Why',
  caseCost: 'Cost',
  caseNextEyebrow: 'Up next',
  caseNextHomeEyebrow: 'Back to home',
  caseNextHomeTitle: 'All demo cases',
  caseNextHomeSubtitle: 'Return to the index — six projects, one page.',
  copyMarkdown: 'copy .md',
  copyMarkdownDone: 'copied',
  heroResumeDownload: 'CV PDF',
  notFoundTitle: 'Page not found',
  notFoundMessage: 'This URL does not exist on this site.',
  notFoundBack: 'Back to home',
  projectStatusLabels: {
    Delivered: 'Delivered',
    Published: 'Published',
    'R&D': 'R&D',
    MVP: 'MVP',
    'Personal tool': 'Personal tool',
    'Open source': 'Open source',
    Demo: 'Demo',
    'Open engine': 'Open engine',
  },
};

export const uiRu: Ui = {
  videoMirror: 'Зеркало на RuTube',
  videoMirrorYoutube: 'Зеркало на YouTube',
  videoPlay: 'Включить видео',
  videoLoading: 'загружается',
  backToHome: 'На главную',
  navBack: 'Главная',
  navCases: 'Кейс',
  sectionAbout: 'Обо мне',
  sectionCases: 'Demo-кейсы',
  sectionTimeline: 'Таймлайн',
  sectionStack: 'Стек',
  caseSectionContext: 'Контекст',
  caseHeroFacts: 'Факты',
  caseSectionArchitecture: 'Архитектура',
  caseSectionDecisions: 'Ключевые инженерные решения',
  caseSectionStack: 'Стек',
  caseSectionLessons: 'Уроки и статус',
  caseLessonsKeep: 'Оставлю как есть',
  caseLessonsChange: 'Поменял бы',
  caseDecision: 'Решение',
  caseWhy: 'Почему',
  caseCost: 'Цена',
  caseNextEyebrow: 'Дальше',
  caseNextHomeEyebrow: 'На главную',
  caseNextHomeTitle: 'Все demo-кейсы',
  caseNextHomeSubtitle: 'Вернуться к индексу — шесть проектов на одной странице.',
  copyMarkdown: 'copy .md',
  copyMarkdownDone: 'copied',
  heroResumeDownload: 'CV PDF',
  notFoundTitle: 'Страница не найдена',
  notFoundMessage: 'Такого URL на этом сайте нет.',
  notFoundBack: 'На главную',
  projectStatusLabels: {
    Delivered: 'Delivered',
    Published: 'Published',
    'R&D': 'R&D',
    MVP: 'MVP',
    'Personal tool': 'Personal tool',
    'Open source': 'Open source',
    Demo: 'Demo',
    'Open engine': 'Open engine',
  },
};
